version: '3.8'

services:
  app:
    build: .
    container_name: babbler-app
    env_file:
      - .env
    ports:
      - '3333:3333'
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: babbler-db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=adonis
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=babbler
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
